[package]
name = "ttyper"
description = "Terminal-based typing test."
version = "1.2.0"
readme = "README.md"
repository = "https://github.com/max-niederman/ttyper.git"
homepage = "https://github.com/max-niederman/ttyper"
license = "MIT"
authors = ["Max Niederman <max@maxniederman.com>"]
edition = "2018"

[dependencies]
crossterm = "0.26"
clap = { version = "4.3", features = ["derive"] }
miette = "5.9"
ratatui = "0.21"
finl_unicode = { version = "1.2", features = ["grapheme_clusters"] }