[package]
name = "ttyper"
description = "Terminal-based typing test."
version = "1.2.0"
readme = "README.md"
repository = "https://github.com/max-niederman/ttyper.git"
homepage = "https://github.com/max-niederman/ttyper"
license = "MIT"
authors = ["Max Niederman <max@maxniederman.com>"]
edition = "2018"

[dependencies]
crossterm = "0.26"
clap = { version = "4.3", features = ["derive"] }
miette = "5.9"
ratatui = "0.21"
unicode-segmentation = "1.10"
rand = "0.8.5"
serde = { version = "1.0.171", features = ["derive"] }
dirs = "5.0.1"
toml = "0.7.6"
