[package]
name = "ttyper"
description = "Terminal-based typing test."
version = "0.1.6"
readme = "README.md"
repository = "https://github.com/max-niederman/ttyper"
license = "MIT"
authors = ["Max Niederman <max@maxniederman.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
tui = "0.14"
termion = "1.5"
ascii = "1.0"

[dependencies.rand]
version = "0.8"
features = ["alloc"]
